services:
  mosquitto:
    image: eclipse-mosquitto:2.0.18
    container_name: mosquitto
    ports:
      - "1883:1883/tcp"
    volumes:
    - ./mosquitto/config:/mosquitto/config
    - ./mosquitto/data:/mosquitto/data
    - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

  subscriber:
    build: ./subscriber
    container_name: subscriber
    environment:
      MQTT_HOST: mosquitto
      MQTT_PORT: "1883"
      MQTT_TOPIC: "esp32/+/data"
      MQTT_USER: "espuser"
      MQTT_PASS: "1234"
      MQTT_CLIENT_ID: "rpi-subscriber"
    depends_on:
      - mosquitto
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.49.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
    privileged: true
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:v1.7.0
    container_name: node-exporter
    command:
      - "--path.rootfs=/host"
    pid: host
    network_mode: host
    volumes:
      - /:/host:ro,rslave
    restart: unless-stopped

volumes:
  prometheus_data:


networks:
  default:
    name: mqtt5-network

