services:
  mosquitto:
    image: eclipse-mosquitto:2.0.18
    container_name: mosquitto-mqtt5
    ports:
      - "1883:1883/tcp"
      - "9001:9001"
    volumes:
    - /home/misu/disertatie_docker_variant/mosquitto/config:/mosquitto/config
    - /home/misu/disertatie_docker_variant/mosquitto/data:/mosquitto/data
    - /home/misu/disertatie_docker_variant/mosquitto/log:/mosquitto/log
    restart: unless-stopped

networks:
  default:
    name: mqtt5-network

