global:
  - scrape_interval: 15

scrape_config:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mosquitto'
    static_configs:
      - targets: [] #tbc
    metrics_path: '/metrics' # tb reviewed
